INSERT INTO category(NAME,CREATED_AT) VALUES('CONE RECHEADO',NOW());
INSERT INTO category(NAME,CREATED_AT) VALUES('PALHA ITALIANA',NOW());
INSERT INTO category(NAME,CREATED_AT) VALUES('TRUFAS',NOW());
INSERT INTO category(NAME,CREATED_AT) VALUES('BOMBONS',NOW());